version: "3"

tasks:
  default:
    cmds:
      - task --list

  build:
    aliases: [b]
    desc: Build
    cmds:
      - uv run pyinstaller build.spec

  format:
    aliases: [f]
    desc: Format the source code
    cmds:
      - uv run ruff format .
      - uv run ruff check . --fix

  lint:
    aliases: [l]
    desc: Static analysis
    cmds:
      - uv ruff check .
      - uv mypy .

  test:
    aliases: [t]
    desc: Test
    cmds:
      - uv pytest .
